Update PR-title.yaml

diff --git a/.github/workflows/PR-title.yaml b/.github/workflows/PR-title.yaml
--- a/.github/workflows/PR-title.yaml
+++ b/.github/workflows/PR-title.yaml
@@ -1,1 +1,26 @@
+name: Execute test cases
+on:
+  pull_request:
+    types: [closed]
 
+jobs:
+  excute-test-cases:
+    name: excute-test-cases
+    if: github.event.pull_request.merged == true
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: execute test case
+        run: |
+          description="${{ github.event.pull_request.body }}"
+          UNCHECKED="\[ \] execute end to end test"
+          MARKED="\[x\] execute end to end test"
+           if echo ${description,,} | grep -q "$MARKED"; then
+            echo "test execution code goes here..."
+            exit 0
+          elif echo ${description,,} | grep -q "$UNCHECKED"; then
+            echo "Checkbox is not checked.. skip execution.."
+          else
+            echo "Checkbox not found in pull request description"
+            exit 1
+          fi
